name: KeibakunWebAPI Github Actions Sample
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  schedule:
    - cron:  '7 14 14 2 *'
jobs:
  scrape:
    name: scrape
    runs-on: macos-13
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: 'node_modules'
          key: node-${{ hashFiles('package-lock.json') }}
          restore-keys: node-

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: scrape netkeiba
        run: |
          npm install
          npx tsx ./NKScraper/scrapingAll_Jra.tsx
